Sprint 5
ClevertecFrontendLab/RodionMar pull request #5
Opened 2024-03-26 14:06 UTC by RodionMar

2024-03-26 14:08 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**buy-tariff-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/RodionMar/1711462116/buy-tariff-success_1440x900.png)
***
**default-profile-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/RodionMar/1711462116/default-profile-page_1440x900.png)
***
**default-settings-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/RodionMar/1711462116/default-settings-page_1440x900.png)
***
**feedbacks with photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/RodionMar/1711462116/feedbacks%20with%20photo_1440x900.png)
***
**modal-big-photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/RodionMar/1711462116/modal-big-photo_1440x900.png)
***
**profile-modal-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/RodionMar/1711462116/profile-modal-error_1440x900.png)
***
**profile-modal-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/RodionMar/1711462116/profile-modal-success_1440x900.png)
***
**settings-page-with-sider_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/RodionMar/1711462116/settings-page-with-sider_360x740.png)
***
**settings-pro-cards_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/RodionMar/1711462116/settings-pro-cards_360x740.png)
***
**settings-sider-pro_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/RodionMar/1711462116/settings-sider-pro_833x900.png)

2024-03-26 19:17 UTC, byshlata reviewed
замечания по коду

2024-03-26 19:17 UTC, byshlata commented on src/components/ProfileForm/ProfileForm.component.tsx
> +    password: string;
необязательные параметры после обязательных

2024-03-26 19:17 UTC, byshlata commented on src/components/ProfileForm/ProfileForm.component.tsx
> +    const emailRules = [
с чего это в теле компонента? это можно и вынести

2024-03-26 19:17 UTC, byshlata commented on src/components/ProfileForm/ProfileForm.component.tsx
> +            pattern: /^(?=.*[a-zа-я])(?=.*[A-ZА-Я])(?=.*\d).{8,}$/,
?

2024-03-26 19:17 UTC, byshlata commented on src/components/ProfileForm/ProfileForm.component.tsx
> +            case FileStatusRnum.ERROR:
где default? он должен быть в любом случае

2024-03-26 19:17 UTC, byshlata commented on src/components/ProfileForm/ProfileForm.component.tsx
> +                                ? uploadButton
сделай это как-то по человечи, вот прям черт пойми что у тебя тут за условия

2024-03-26 19:17 UTC, byshlata commented on src/components/ProfileForm/ProfileForm.component.tsx
> +                            listType={windowWidth > 360 ? 'picture-card' : 'picture'}
360 в константы

2024-03-26 19:17 UTC, byshlata commented on src/components/ProfileForm/index.module.scss
> +    gap: 24px;
в переменные

2024-03-26 19:17 UTC, byshlata commented on src/components/ProfileForm/index.module.scss
> +        margin-top: 16px;
в переменные

2024-03-26 19:17 UTC, byshlata commented on src/components/ResultModal/ResultModal.component.tsx
>      return (
?

2024-03-26 19:17 UTC, byshlata commented on src/components/SettingsDrawer/SettingsDrawer.component.tsx
> +        { title: 'Участие в марафонах', includeInFree: false, includeInPro: true },
за компонент лучше вынеси

2024-03-26 19:17 UTC, byshlata commented on src/components/SettingsDrawer/SettingsDrawer.component.tsx
> +    const featureList = featureItemsData.map((item, index) => (
а зачемэто чать тут,  а не ниже?

2024-03-26 19:17 UTC, byshlata commented on src/components/SettingsDrawer/index.module.scss
> +        padding: 24px 32px 16px;
в переменные

2024-03-26 19:17 UTC, byshlata commented on src/components/SettingsDrawer/index.module.scss
> +        border-radius: 8px 0 0 8px;
в переменные

2024-03-26 19:17 UTC, byshlata commented on src/components/SettingsDrawer/index.module.scss
> +            border-radius: 10px;
переменные

2024-03-26 19:17 UTC, byshlata commented on src/components/SettingsSwitch/SettingsSwitch.component.tsx
> +    switchDataTestId: string;
в отдельный тип

2024-03-26 19:17 UTC, byshlata commented on src/components/SettingsSwitch/SettingsSwitch.component.tsx
> +    return (
?

2024-03-26 19:17 UTC, byshlata commented on src/components/Sider/Sider.component.tsx
>          } else if (windowWidth > 705) {
705 in constants

2024-03-26 19:17 UTC, byshlata commented on src/pages/auth/constants/auth-endpoints.enum.ts
> +    AUTH_CONFIRM_EMAIL = `/auth/confirm-email`,
можно еще отдельно auth вынести, а то дублируется

2024-03-27 05:42 UTC, VitalyHanchar commented on package.json
>    },
![image](https://github.com/ClevertecFrontendLab/RodionMar/assets/122732222/39fe5ab0-b7a0-44bf-9eb2-c902697d50fa)
Макет
![image](https://github.com/ClevertecFrontendLab/RodionMar/assets/122732222/674e46d3-d894-4b9f-9b01-9941bcb099ad)

2024-03-27 05:56 UTC, VitalyHanchar requested changes
-

2024-03-27 10:26 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**buy-tariff-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/RodionMar/1711535198/buy-tariff-success_1440x900.png)
***
**default-profile-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/RodionMar/1711535198/default-profile-page_1440x900.png)
***
**default-settings-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/RodionMar/1711535198/default-settings-page_1440x900.png)
***
**feedbacks with photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/RodionMar/1711535198/feedbacks%20with%20photo_1440x900.png)
***
**modal-big-photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/RodionMar/1711535198/modal-big-photo_1440x900.png)
***
**profile-modal-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/RodionMar/1711535198/profile-modal-error_1440x900.png)
***
**profile-modal-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/RodionMar/1711535198/profile-modal-success_1440x900.png)
***
**settings-page-with-sider_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/RodionMar/1711535198/settings-page-with-sider_360x740.png)
***
**settings-pro-cards_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/RodionMar/1711535198/settings-pro-cards_360x740.png)
***
**settings-sider-pro_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/RodionMar/1711535198/settings-sider-pro_833x900.png)

2024-03-27 10:27 UTC, byshlata approved these changes

2024-03-27 10:28 UTC, VitalyHanchar approved these changes

2024-03-27 10:28 UTC, merged